--- sys/osxaudio/gstatenc.c	2026-04-08 03:02:23.000000000 +0800
+++ sys/osxaudio/gstatenc.c	2026-05-07 06:45:20.000000000 +0800
@@ -133,26 +133,6 @@
       GST_AUDIO_CHANNEL_POSITION_SURROUND_LEFT,
       GST_AUDIO_CHANNEL_POSITION_SURROUND_RIGHT,
       GST_AUDIO_CHANNEL_POSITION_LFE1 }}, {
-    /* C L R Ls Rs Rls Rrs LFE */
-    8, kAudioChannelLayoutTag_AAC_7_1_B, {
-      GST_AUDIO_CHANNEL_POSITION_FRONT_CENTER,
-      GST_AUDIO_CHANNEL_POSITION_FRONT_LEFT,
-      GST_AUDIO_CHANNEL_POSITION_FRONT_RIGHT,
-      GST_AUDIO_CHANNEL_POSITION_SURROUND_LEFT,
-      GST_AUDIO_CHANNEL_POSITION_SURROUND_RIGHT,
-      GST_AUDIO_CHANNEL_POSITION_REAR_LEFT,
-      GST_AUDIO_CHANNEL_POSITION_REAR_RIGHT,
-      GST_AUDIO_CHANNEL_POSITION_LFE1 }}, {
-    /* C L R Ls Rs LFE Vhl Vhr */
-    8, kAudioChannelLayoutTag_AAC_7_1_C, {
-      GST_AUDIO_CHANNEL_POSITION_FRONT_CENTER,
-      GST_AUDIO_CHANNEL_POSITION_FRONT_LEFT,
-      GST_AUDIO_CHANNEL_POSITION_FRONT_RIGHT,
-      GST_AUDIO_CHANNEL_POSITION_SURROUND_LEFT,
-      GST_AUDIO_CHANNEL_POSITION_SURROUND_RIGHT,
-      GST_AUDIO_CHANNEL_POSITION_LFE1,
-      GST_AUDIO_CHANNEL_POSITION_TOP_FRONT_LEFT,
-      GST_AUDIO_CHANNEL_POSITION_TOP_FRONT_RIGHT }}, {
     /* Only used when iterating through all positions */
     0, kAudioChannelLayoutTag_Unknown, { 0 } }
 };
