#!/bin/bash

if [ -n "$DYLD_LIBRARY_PATH" ]; then
   DYLD_LIBRARY_PATH=/opt/local/lib/libgcc:${DYLD_LIBRARY_PATH}
else
   DYLD_LIBRARY_PATH=/opt/local/lib/libgcc
fi
export DYLD_LIBRARY_PATH

cd /opt/local/share/musikcube/
exec ./musikcube "$@"
